# Generated by Django 6.0 on 2025-12-12 02:07

import chatbot.models
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnncAll",
            fields=[
                (
                    "annc_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="공고 ID"
                    ),
                ),
                (
                    "annc_title",
                    models.CharField(max_length=200, verbose_name="공고 제목"),
                ),
                (
                    "annc_url",
                    models.URLField(
                        max_length=2000, unique=True, verbose_name="공고 URL"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="공고 생성 일자"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="공고 수정 일자"),
                ),
                ("corp_cd", models.CharField(max_length=10, verbose_name="공사 코드")),
                (
                    "annc_type",
                    models.CharField(max_length=50, verbose_name="공고 유형"),
                ),
                (
                    "annc_dtl_type",
                    models.CharField(max_length=20, verbose_name="공고 유형 상세"),
                ),
                ("annc_region", models.CharField(max_length=50, verbose_name="지역")),
                (
                    "annc_pblsh_dt",
                    models.CharField(max_length=50, verbose_name="게시일"),
                ),
                (
                    "annc_deadline_dt",
                    models.CharField(max_length=50, verbose_name="마감일"),
                ),
                (
                    "annc_status",
                    models.CharField(max_length=20, verbose_name="공고 상태"),
                ),
                (
                    "service_status",
                    models.CharField(max_length=20, verbose_name="서비스 상태"),
                ),
            ],
            options={
                "verbose_name": "공고 전체 테이블",
                "verbose_name_plural": "공고 전체 테이블",
                "db_table": "annc_all",
            },
        ),
        migrations.CreateModel(
            name="AnncLhTemp",
            fields=[
                (
                    "temp_id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="장고를 위한 SEQ",
                    ),
                ),
                ("batch_id", models.UUIDField(verbose_name="배치 ID")),
                ("batch_seq", models.IntegerField(verbose_name="배치 SEQ")),
                (
                    "annc_title",
                    models.CharField(max_length=200, verbose_name="공고 제목"),
                ),
                ("annc_url", models.TextField(verbose_name="공고 URL")),
                (
                    "batch_start_dttm",
                    models.DateTimeField(verbose_name="배치 등록 시간"),
                ),
                (
                    "batch_end_dttm",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="배치 완료 시간"
                    ),
                ),
                (
                    "batch_status",
                    models.CharField(max_length=10, verbose_name="배치 상태"),
                ),
                (
                    "annc_type",
                    models.CharField(max_length=50, verbose_name="공고 유형"),
                ),
                (
                    "annc_dtl_type",
                    models.CharField(max_length=20, verbose_name="공고 유형 상세"),
                ),
                ("annc_region", models.CharField(max_length=50, verbose_name="지역")),
                (
                    "annc_pblsh_dt",
                    models.CharField(max_length=50, verbose_name="게시일"),
                ),
                (
                    "annc_deadline_dt",
                    models.CharField(max_length=50, verbose_name="마감일"),
                ),
                (
                    "annc_status",
                    models.CharField(max_length=20, verbose_name="공고 상태"),
                ),
                (
                    "lh_pan_id",
                    models.CharField(max_length=30, verbose_name="공고 식별 ID"),
                ),
                (
                    "lh_ais_tp_cd",
                    models.CharField(max_length=10, verbose_name="공고 유형 코드"),
                ),
                (
                    "lh_upp_ais_tp_cd",
                    models.CharField(max_length=10, verbose_name="상위 공고 유형 코드"),
                ),
                (
                    "lh_ccr_cnnt_sys_ds_cd",
                    models.CharField(
                        max_length=10, verbose_name="연계 시스템 구분 코드"
                    ),
                ),
                (
                    "lh_ls_sst",
                    models.CharField(max_length=50, verbose_name="목록 상의 상태/순서"),
                ),
            ],
            options={
                "verbose_name": "LH 크롤링 배치 임시",
                "verbose_name_plural": "LH 크롤링 배치 임시 기록",
                "db_table": "annc_lh_temp",
            },
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="채팅 ID"
                    ),
                ),
                ("session_key", models.UUIDField(unique=True, verbose_name="세션 키")),
                (
                    "user_key",
                    models.CharField(max_length=100, verbose_name="사용자 고유키"),
                ),
                (
                    "title",
                    models.CharField(
                        default="새로운 채팅", max_length=200, verbose_name="채팅 제목"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="최근 업데이트 일시"
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 세션",
                "verbose_name_plural": "채팅 세션 목록",
                "db_table": "chat",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AnncFiles",
            fields=[
                (
                    "file_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="공고 파일 ID"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=500, verbose_name="공고 파일명"),
                ),
                (
                    "file_type",
                    models.CharField(max_length=10, verbose_name="공고 파일 유형"),
                ),
                (
                    "file_path",
                    models.CharField(
                        max_length=2000, null=True, verbose_name="공고 파일 경로"
                    ),
                ),
                (
                    "file_ext",
                    models.CharField(max_length=10, verbose_name="공고 파일 확장자"),
                ),
                ("file_size", models.IntegerField(verbose_name="공고 파일 사이즈")),
                (
                    "annc_id",
                    models.ForeignKey(
                        db_column="annc_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot.anncall",
                        verbose_name="공고 ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "공고 파일",
                "verbose_name_plural": "공고 파일",
                "db_table": "annc_files",
                "unique_together": {("file_id", "annc_id")},
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="기록 ID"
                    ),
                ),
                ("sequence", models.IntegerField(verbose_name="메시지 순서")),
                ("message", models.TextField(verbose_name="메시지 내용")),
                ("prompt", models.TextField(verbose_name="프롬프트 내용")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("system", "System Message"),
                            ("user", "User Message"),
                            ("bot", "Bot Response"),
                        ],
                        max_length=6,
                        verbose_name="메시지 유형",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="chatbot.chat",
                        verbose_name="채팅 세션",
                    ),
                ),
            ],
            options={
                "db_table": "chat_message",
                "ordering": ["chat", "sequence"],
                "unique_together": {("chat", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="DocChunks",
            fields=[
                (
                    "chunk_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="청크 ID"
                    ),
                ),
                (
                    "chunk_type",
                    models.CharField(max_length=20, verbose_name="청크 타입"),
                ),
                ("chunk_text", models.TextField(verbose_name="청크 텍스트")),
                ("page_num", models.SmallIntegerField(verbose_name="페이지 번호")),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=1536, verbose_name="임베딩 벡터"
                    ),
                ),
                ("metadata", models.JSONField(verbose_name="메타데이터")),
                (
                    "fts_vector",
                    chatbot.models.TSVectorField(
                        blank=True, null=True, verbose_name="전문 검색 벡터"
                    ),
                ),
                (
                    "annc_id",
                    models.ForeignKey(
                        db_column="annc_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot.anncall",
                        verbose_name="공고 ID",
                    ),
                ),
                (
                    "file_id",
                    models.ForeignKey(
                        db_column="file_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot.anncfiles",
                        verbose_name="공고 파일 ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "공고 파일 청크 벡터",
                "verbose_name_plural": "공고 파일 청크 벡터",
                "db_table": "doc_chunks",
                "unique_together": {("chunk_id", "file_id", "annc_id")},
            },
        ),
    ]
