--
-- PostgreSQL database dump
--

\restrict ob31DODI27U6I0DhDPh5mTWFYGaXQ4xSbQkSM3kVgVlkeMMyWPJtDIAuWGe9kcs

-- Dumped from database version 17.7 (Debian 17.7-3.pgdg12+1)
-- Dumped by pg_dump version 17.7 (Debian 17.7-3.pgdg12+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


--
-- Name: doc_chunks_fts_trigger(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.doc_chunks_fts_trigger() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
                BEGIN
                    NEW.fts_vector := to_tsvector('simple', NEW.chunk_text);
                    RETURN NEW;
                END
                $$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: annc_all; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.annc_all (
    annc_id bigint NOT NULL,
    annc_title character varying(200) NOT NULL,
    annc_url character varying(2000) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    corp_cd character varying(10) NOT NULL,
    annc_type character varying(50) NOT NULL,
    annc_dtl_type character varying(20) NOT NULL,
    annc_region character varying(50) NOT NULL,
    annc_pblsh_dt character varying(50) NOT NULL,
    annc_deadline_dt character varying(50) NOT NULL,
    annc_status character varying(20) NOT NULL,
    service_status character varying(20) NOT NULL
);


--
-- Name: annc_all_annc_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.annc_all ALTER COLUMN annc_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.annc_all_annc_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: annc_files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.annc_files (
    file_id bigint NOT NULL,
    file_name character varying(500) NOT NULL,
    file_type character varying(10) NOT NULL,
    file_path character varying(2000),
    file_ext character varying(10) NOT NULL,
    file_size integer NOT NULL,
    annc_id bigint NOT NULL
);


--
-- Name: annc_files_file_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.annc_files ALTER COLUMN file_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.annc_files_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: annc_lh_temp; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.annc_lh_temp (
    temp_id bigint NOT NULL,
    batch_id uuid NOT NULL,
    batch_seq integer NOT NULL,
    annc_title character varying(200) NOT NULL,
    annc_url text NOT NULL,
    batch_start_dttm timestamp with time zone NOT NULL,
    batch_end_dttm timestamp with time zone,
    batch_status character varying(10) NOT NULL,
    annc_type character varying(50) NOT NULL,
    annc_dtl_type character varying(20) NOT NULL,
    annc_region character varying(50) NOT NULL,
    annc_pblsh_dt character varying(50) NOT NULL,
    annc_deadline_dt character varying(50) NOT NULL,
    annc_status character varying(20) NOT NULL,
    lh_pan_id character varying(30) NOT NULL,
    lh_ais_tp_cd character varying(10) NOT NULL,
    lh_upp_ais_tp_cd character varying(10) NOT NULL,
    lh_ccr_cnnt_sys_ds_cd character varying(10) NOT NULL,
    lh_ls_sst character varying(50) NOT NULL
);


--
-- Name: annc_lh_temp_temp_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.annc_lh_temp ALTER COLUMN temp_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.annc_lh_temp_temp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat (
    id bigint NOT NULL,
    session_key uuid NOT NULL,
    user_key character varying(100) NOT NULL,
    title character varying(200) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: chat_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_message; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_message (
    id bigint NOT NULL,
    sequence integer NOT NULL,
    message text NOT NULL,
    prompt text NOT NULL,
    message_type character varying(6) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    chat_id bigint NOT NULL
);


--
-- Name: chat_message_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doc_chunks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.doc_chunks (
    chunk_id bigint NOT NULL,
    chunk_type character varying(20) NOT NULL,
    chunk_text text NOT NULL,
    page_num smallint NOT NULL,
    embedding public.vector(1536) NOT NULL,
    metadata jsonb NOT NULL,
    fts_vector tsvector,
    annc_id bigint NOT NULL,
    file_id bigint NOT NULL
);


--
-- Name: doc_chunks_chunk_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.doc_chunks ALTER COLUMN chunk_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doc_chunks_chunk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: annc_all annc_all_annc_url_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annc_all
    ADD CONSTRAINT annc_all_annc_url_key UNIQUE (annc_url);


--
-- Name: annc_all annc_all_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annc_all
    ADD CONSTRAINT annc_all_pkey PRIMARY KEY (annc_id);


--
-- Name: annc_files annc_files_file_id_annc_id_d8167e21_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annc_files
    ADD CONSTRAINT annc_files_file_id_annc_id_d8167e21_uniq UNIQUE (file_id, annc_id);


--
-- Name: annc_files annc_files_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annc_files
    ADD CONSTRAINT annc_files_pkey PRIMARY KEY (file_id);


--
-- Name: annc_lh_temp annc_lh_temp_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annc_lh_temp
    ADD CONSTRAINT annc_lh_temp_pkey PRIMARY KEY (temp_id);


--
-- Name: chat_message chat_message_chat_id_sequence_df006b3a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_chat_id_sequence_df006b3a_uniq UNIQUE (chat_id, sequence);


--
-- Name: chat_message chat_message_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_pkey PRIMARY KEY (id);


--
-- Name: chat chat_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT chat_pkey PRIMARY KEY (id);


--
-- Name: chat chat_session_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT chat_session_key_key UNIQUE (session_key);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: doc_chunks doc_chunks_chunk_id_file_id_annc_id_a91560a3_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doc_chunks
    ADD CONSTRAINT doc_chunks_chunk_id_file_id_annc_id_a91560a3_uniq UNIQUE (chunk_id, file_id, annc_id);


--
-- Name: doc_chunks doc_chunks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doc_chunks
    ADD CONSTRAINT doc_chunks_pkey PRIMARY KEY (chunk_id);


--
-- Name: annc_all_annc_url_2d790bc7_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX annc_all_annc_url_2d790bc7_like ON public.annc_all USING btree (annc_url varchar_pattern_ops);


--
-- Name: annc_files_annc_id_4962fe44; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX annc_files_annc_id_4962fe44 ON public.annc_files USING btree (annc_id);


--
-- Name: chat_message_chat_id_21483fa7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chat_message_chat_id_21483fa7 ON public.chat_message USING btree (chat_id);


--
-- Name: doc_chunks_annc_id_7049600c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX doc_chunks_annc_id_7049600c ON public.doc_chunks USING btree (annc_id);


--
-- Name: doc_chunks_file_id_e1ca55b2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX doc_chunks_file_id_e1ca55b2 ON public.doc_chunks USING btree (file_id);


--
-- Name: annc_files annc_files_annc_id_4962fe44_fk_annc_all_annc_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annc_files
    ADD CONSTRAINT annc_files_annc_id_4962fe44_fk_annc_all_annc_id FOREIGN KEY (annc_id) REFERENCES public.annc_all(annc_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chat_message chat_message_chat_id_21483fa7_fk_chat_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_chat_id_21483fa7_fk_chat_id FOREIGN KEY (chat_id) REFERENCES public.chat(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doc_chunks doc_chunks_annc_id_7049600c_fk_annc_all_annc_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doc_chunks
    ADD CONSTRAINT doc_chunks_annc_id_7049600c_fk_annc_all_annc_id FOREIGN KEY (annc_id) REFERENCES public.annc_all(annc_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doc_chunks doc_chunks_file_id_e1ca55b2_fk_annc_files_file_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doc_chunks
    ADD CONSTRAINT doc_chunks_file_id_e1ca55b2_fk_annc_files_file_id FOREIGN KEY (file_id) REFERENCES public.annc_files(file_id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict ob31DODI27U6I0DhDPh5mTWFYGaXQ4xSbQkSM3kVgVlkeMMyWPJtDIAuWGe9kcs

